### ISSUE TITLE
ValueError: only one element tensors can be converted to Python scalars

### ISSUE THREAD

**Issue by strakehyr** [timeseriesAI/tsai#300]
I previously (with version 2.22), did not have an issue when making predictions. However, now, when trying to save a model, and then loading the model to get predictions, I get the aforementioned error:

```
Traceback (most recent call last):               

  File "C:\Users\user\AppData\Local\Temp/ipykernel_24144/3000019384.py", line 36, in <module>
    probas, _, preds = learn.get_X_preds(X)

  File "C:\Users\user\Anaconda3\lib\site-packages\tsai\inference.py", line 23, in get_X_preds
    output[2 + with_input] = self.dls.tls[-1].tfms.decode(output[2 + with_input])

  File "C:\Users\user\Anaconda3\lib\site-packages\fastcore\transform.py", line 208, in decode
    if full: return compose_tfms(o, tfms=self.fs, is_enc=False, reverse=True, split_idx=self.split_idx)

  File "C:\Users\user\Anaconda3\lib\site-packages\fastcore\transform.py", line 150, in compose_tfms
    x = f(x, **kwargs)

  File "C:\Users\user\Anaconda3\lib\site-packages\fastcore\transform.py", line 74, in decode
    def decode  (self, x, **kwargs): return self._call('decodes', x, **kwargs)

  File "C:\Users\user\Anaconda3\lib\site-packages\fastcore\transform.py", line 83, in _call
    return self._do_call(getattr(self, fn), x, **kwargs)

  File "C:\Users\user\Anaconda3\lib\site-packages\fastcore\transform.py", line 89, in _do_call
    return retain_type(f(x, **kwargs), x, ret)

  File "C:\Users\user\Anaconda3\lib\site-packages\fastcore\dispatch.py", line 118, in __call__
    return f(*args, **kwargs)

  File "C:\Users\user\Anaconda3\lib\site-packages\tsai\data\core.py", line 108, in decodes
    def decodes(self, o): return TitledFloat(o) if o.ndim==0 else TitledTuple(o_.item() for o_ in o)

  File "C:\Users\user\Anaconda3\lib\site-packages\fastcore\basics.py", line 632, in __new__
    try: x = tuple(iter(x))

  File "C:\Users\user\Anaconda3\lib\site-packages\tsai\data\core.py", line 108, in <genexpr>
    def decodes(self, o): return TitledFloat(o) if o.ndim==0 else TitledTuple(o_.item() for o_ in o)

  File "C:\Users\user\Anaconda3\lib\site-packages\fastai\torch_core.py", line 340, in __torch_function__
    res = super().__torch_function__(func, types, args=args, kwargs=kwargs)

  File "C:\Users\user\Anaconda3\lib\site-packages\torch\_tensor.py", line 1051, in __torch_function__
    ret = func(*args, **kwargs)

ValueError: only one element tensors can be converted to Python scalars
```

I've used both:

```
learn.save_all(save_path)
[...]
learn = load_all(model_path)     
X, y = SlidingWindow(look_back, get_x = list(df.columns), get_y=[], horizon=horizon)(df)
probas, _, preds = learn.get_X_preds(X)
```
and, as proposed by @oguiza:

```
learn.export(model_path)
[...]
from tsai.inference import load_learner
learn = load_learner(model_path)     
X, y = SlidingWindow(look_back, get_x = list(df.columns), get_y=[], horizon=horizon)(df)
probas, _, preds = learn.get_X_preds(X)
```
They both give the same error.

**Comment by jlequeux** [comment]
Hi, 
I have the same issue with a model I just trained (`TSForecaster` with `ResCNN`)
It is working fine when the `horizon` of the `SlidingWindow` is 1, but it raises the same error (`ValueError: only one element tensors can be converted to Python scalars`) when the `horizon` is 2 or higher.

**Comment by oguiza** [comment]
I've just updated the repo with some updated code that I believe will fix this issue. 
It'd be good if you could update tsai using 

```bash
!pip install git+https://github.com/timeseriesAI/tsai.git -Uqq
# ⚠️ REMEMBER TO RESTART (NOT RECONNECT/ RESET) THE KERNEL/ RUNTIME ONCE THE INSTALLATION IS FINISHED
```
 and test it again.

**Comment by strakehyr** [comment]
Did, and now from trying to load old models , I get:

`AttributeError: Can't get attribute 'create_lin_3d_head' on <module 'tsai.models.layers' from 'C:\\Users\\user\\Anaconda3\\lib\\site-packages\\tsai\\models\\layers.py'>`

**Comment by oguiza** [comment]
Sorry about that. I've updated create_lin_3d_head and create_conv_lin_3d_head to take any number of dimensions so changed the name to create_lin_nd_head and create_conv_lin_nd_head. I've added them back to the repo for backward compatibility. Please, update tsai from GitHub and try it again if you can.

**Comment by strakehyr** [comment]
Hi @oguiza, still getting the same issue. I've reinstalled twice with your command:
> I've just updated the repo with some updated code that I believe will fix this issue. It'd be good if you could update tsai using
> 
> ```shell
> !pip install git+https://github.com/timeseriesAI/tsai.git -Uqq
> # ⚠️ REMEMBER TO RESTART (NOT RECONNECT/ RESET) THE KERNEL/ RUNTIME ONCE THE INSTALLATION IS FINISHED
> ```
> 
> and test it again.

, and even downgraded to 0.2.23 before, and seem to be still getting:
 `AttributeError: Can't get attribute 'create_lin_3d_head' on <module 'tsai.models.layers' from 'C:\\Users\\user\\Anaconda3\\lib\\site-packages\\tsai\\models\\layers.py'>`

I am probably missing something.

**Comment by oguiza** [comment]
😬 
I forgot to add something when pushed the commit. My apologies.
I've now confirmed that create_lin_3d_head is in the repo. It should work now.

**Comment by strakehyr** [comment]
Thanks again for the quick response. The support for this library is amazing. 

Anyway, the ` create_lin_3d_head ` issue is now solved, and loading models works (At least with load_all). However, the original  issue concerning predictions still persists:

> ```
> Traceback (most recent call last):               
> 
>   File "C:\Users\user\AppData\Local\Temp/ipykernel_24144/3000019384.py", line 36, in <module>
>     probas, _, preds = learn.get_X_preds(X)
> 
>   File "C:\Users\user\Anaconda3\lib\site-packages\tsai\inference.py", line 23, in get_X_preds
>     output[2 + with_input] = self.dls.tls[-1].tfms.decode(output[2 + with_input])
> 
>   File "C:\Users\user\Anaconda3\lib\site-packages\fastcore\transform.py", line 208, in decode
>     if full: return compose_tfms(o, tfms=self.fs, is_enc=False, reverse=True, split_idx=self.split_idx)
> 
>   File "C:\Users\user\Anaconda3\lib\site-packages\fastcore\transform.py", line 150, in compose_tfms
>     x = f(x, **kwargs)
> 
>   File "C:\Users\user\Anaconda3\lib\site-packages\fastcore\transform.py", line 74, in decode
>     def decode  (self, x, **kwargs): return self._call('decodes', x, **kwargs)
> 
>   File "C:\Users\user\Anaconda3\lib\site-packages\fastcore\transform.py", line 83, in _call
>     return self._do_call(getattr(self, fn), x, **kwargs)
> 
>   File "C:\Users\user\Anaconda3\lib\site-packages\fastcore\transform.py", line 89, in _do_call
>     return retain_type(f(x, **kwargs), x, ret)
> 
>   File "C:\Users\user\Anaconda3\lib\site-packages\fastcore\dispatch.py", line 118, in __call__
>     return f(*args, **kwargs)
> 
>   File "C:\Users\user\Anaconda3\lib\site-packages\tsai\data\core.py", line 108, in decodes
>     def decodes(self, o): return TitledFloat(o) if o.ndim==0 else TitledTuple(o_.item() for o_ in o)
> 
>   File "C:\Users\user\Anaconda3\lib\site-packages\fastcore\basics.py", line 632, in __new__
>     try: x = tuple(iter(x))
> 
>   File "C:\Users\user\Anaconda3\lib\site-packages\tsai\data\core.py", line 108, in <genexpr>
>     def decodes(self, o): return TitledFloat(o) if o.ndim==0 else TitledTuple(o_.item() for o_ in o)
> 
>   File "C:\Users\user\Anaconda3\lib\site-packages\fastai\torch_core.py", line 340, in __torch_function__
>     res = super().__torch_function__(func, types, args=args, kwargs=kwargs)
> 
>   File "C:\Users\user\Anaconda3\lib\site-packages\torch\_tensor.py", line 1051, in __torch_function__
>     ret = func(*args, **kwargs)
> 
> ValueError: only one element tensors can be converted to Python scalars
> ```

**Comment by oguiza** [comment]
Ok, so we are back to square one 🙂

I don't know where this issue comes from. I'd need to see the code that you are using or a snippet that reproduces this issue. 

I've tested a classification task with multiple targets and seems to work well: 

```bash 
X, y, splits = get_UCR_data('LSST', split_data=False)
y_multi = y.reshape(-1,1).repeat(3,1)

tfms = [None, TSCategorize()]
batch_tfms = TSStandardize(by_sample=True)

dls = get_ts_dls(X, y_multi, splits=splits, tfms=tfms, batch_tfms=batch_tfms)

learn = ts_learner(dls, InceptionTimePlus, cbs=[ShowGraph()])
learn.fit_one_cycle(1, 1e-2)
learn.get_X_preds(X, y_multi)
```

**Comment by strakehyr** [comment]
It's a Regression forecasting problem using TSTPlus, as shown below:
```
X, y = SlidingWindow(look_back, get_x = list(df.iloc[:,n_outputs:].columns), get_y = (df.iloc[:,0].name), horizon=horizon)(df)
y = y.reshape(y.shape[0], 1, y.shape[1])
splits = get_splits(y, n_splits=1, valid_size=.2, shuffle=True)
check_data(X, y, splits)
tfms  = [None, [TSRegression()]]
batch_tfms = TSStandardize(by_var=True)
dls = get_ts_dls(X, y, splits=splits, tfms=tfms, batch_tfms=batch_tfms)

n_layers = 1
ks = 7
d_model = 192
num_epochs = 90
cbs=ShowGraph() 
learn = ts_learner(dls, TSTPlus, ks = ks, n_layers = n_layers, d_model = d_model, 
                   opt_func = SGD, loss_func = mse,
                   metrics=[mae, mse], cbs=cbs)
lr = learn.lr_find()[0]    
learn.fit_one_cycle(num_epochs, lr)
learn.save_all(save_path)
```
[...]
```
learn = learn.load(save_path)
probas, _, preds = learn.get_X_preds(X[splits[1]])
```

**Comment by oguiza** [comment]
Ok, I've identified the issue. There was a bug that should be fixed now 🤞.
You can try it again.
Here's the code I've used for testing: 

```bash
X, y, splits = get_regression_data('Covid3Month', split_data=False)
y = y.reshape(-1, 1, 1).repeat(3,2)

tfms  = [None, [TSRegression()]]
batch_tfms = TSStandardize(by_var=True)
dls = get_ts_dls(X, y, splits=splits, tfms=tfms, batch_tfms=batch_tfms)

n_layers = 1
ks = 7
d_model = 192
num_epochs = 1
cbs=ShowGraph() 
learn = ts_learner(dls, TSTPlus, ks = ks, n_layers = n_layers, d_model = d_model, 
                   opt_func = SGD, loss_func = mse, 
                   metrics=[mae, mse], cbs=cbs)
lr = learn.lr_find()[0]    
learn.fit_one_cycle(num_epochs, lr)

probas, _, preds = learn.get_X_preds(X[splits[1]])
probas, _, preds
````
